---
- name: Create a volume for building
  containers.podman.podman_volume:
    state: present
    name: ee_vol
  register: builder_vol

- name: Pull the image
  containers.podman.podman_image:
    name: quay.io/fedora/fedora-minimal:latest

- name: Copy files to volume
  ansible.builtin.template:
    src: "{{ ee_item }}.j2"
    dest: "{{ builder_vol.volume['Mountpoint'] }}/{{ ee_item }}"
    owner: 'zach'
    group: 'zach'
    mode: 0644
  loop:
    - 'execution_environment.yml'
    - 'requirements.yml'
    - 'ansible.cfg'

- name: Create the container 
  containers.podman.podman_container:
    name: ee_builder
    image: quay.io/fedora/fedora-minimal:latest
    command: redis-server --appendonly yes
    state: started
    recreate: true
    volume: 
      - ee_vol:/home/zach/ee_build
    user: 'zach'
    rm: true