---
- name: devel | Install devel packages
  ansible.builtin.dnf:
    state: latest
    name: "{{ languages }}"

- name: devel | Install packager packages
  ansible.builtin.dnf:
    state: latest
    name: "{{ packaging }}"
  when: inventory_hostname in groups.zach

- name: devel | Install the pretty fonts
  ansible.builtin.dnf:
    name: "{{ nice_mono_fonts }}"
    state: latest
  when: inventory_hostname in groups.zach