---
- name: install nginx
  dnf:
    name: nginx
    state: latest

- name: enable nginx service
  systemd:
    name: nginx.service
    state: started
    enabled: yes
    daemon-reload: yes

- name: template the configuration
  template:
    src:
    dest:
  notify: reload_and_restart

