---
- include_vars: "{{ ansible_hostname }}.yml"
- include_vars: "{{ ansible_distribution_file_variety }}.yml"
- include_vars: default.yml

- name: make the etc dir
  file:
    path: /etc/nebula
    state: directory

- name: move host certs
  copy:
    src: "{{ ansible_hostname }}.{{ item }}"
    dest: "/etc/nebula/{{ ansible_hostname }}.{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - 'crt'
    - 'key'

- name: move ca crt
  copy:
    src: ca.crt
    dest: /etc/nebula/ca.crt
    owner: root
    group: root
    mode: 0644

- name: move binary
  copy:
    src: "{{ ansible_architecture }}/nebula"
    dest: /usr/local/bin/nebula
    owner: root
    group: root
    mode: 0755

- name: add to path for root
  shell: echo 'PATH=$PATH:/usr/local/bin:$HOME/.local/bin' >> /root/.bash_profile 

- name: template the config
  template:
    src: config.yml.j2
    dest: /etc/nebula/config.yml
    owner: root
    group: root
    mode: 0644

- name: open the port
  firewalld:
    port: 4242/udp
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_distribution != 'Debian'

- name: copy the service file
  copy:
    src: nebula.service
    dest: "{{ systemd_service_dir }}/nebula.service"
    owner: root
    group: root
    mode: 0644

- name: start and enable nebula service
  systemd:
    name: nebula.service
    state: started
    enabled: true
    daemon-reload: yes
