---
- name: Create a config volume
  containers.podman.podman_volume:
    name: nginx_config
  register: config_vol

- name: Copy the configuration files
  ansible.builtin.copy:
    src: "{{ role_path }}/files/nginx"
    dest: "{{ config_vol.volume.Mountpoint }}/"
    owner: root
    group: root
    mode: 0644

- name: Create the nginx container
  containers.podman.podman_container:
    name: nginx_rproxy
    image: docker.io/library/nginx
    state: started
    recreate: true
    command: /usr/sbin/nginx
    tty: yes
    cap_add:
      - 'NET_ADMIN'
      - 'NET_RAW'
    expose: "{{ expose_ports }}"
    publish: "{{ publish_ports }}"
    volume:
      - "{{ config_vol.volume.Mountpoint }}:/etc/nginx"
    env:
      'TZ': 'America/NewYork'
      'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    generate_systemd:
      restart_policy: always
      time: 120
      names: true
      container_prefix: pdmn
      separator: "_"
  register: server_container
  
- name: Create zone internal
  firewalld:
    zone: tailscale
    permanent: yes
    state: present

- name: Enable zone internal for tailscale0
  firewalld:
    zone: tailscale
    permanent: yes
    immediate: yes
    interface: tailscale0
    state: enabled

- name: Allow services tailscale zone
  firewalld:
    zone: tailscale 
    permanent: yes
    immediate: yes
    state: enabled
    service: "{{ item }}"
  loop:
    - 'ssh'
    - 'http'
    - 'https'
    - 'dns'
    - 'dns-over-tls'

- name: Configure tailscale zone ports
  firewalld:
    zone: tailscale 
    permanent: yes
    immediate: yes
    port: "{{ item }}"
    state: enabled
  loop: "{{ publish_ports }}"
