---
- name: reset modules
  command: "dnf module reset @{{ container_module }} -y"

- name: enable module
  command: "dnf module enable @{{ container_module }}:{{ mod_version }} -y"

- name: install packages
  dnf:
    name: "{{ podman_pkgs }}"
    state: latest

- name: activate podman user service
  systemd:
    name: podman
    state: restarted
    daemon-reload: yes
    scope: user
  become_user: zach

- name: activate podman system service
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon-reload: yes
  loop:
    - 'cri-o'
    - 'podman'