---
- name: include distro specific vars
  include_vars: "{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution_major_version not in ['35', '9']

- name: reset modules
  command: "dnf module reset {{ item | split(':') | first }} -y"
  when: ansible_distribution_major_version != '9'
  loop: "{{ container_modules }}"

- name: enable module
  command: "dnf module enable {{ item }} -y"
  when: ansible_distribution_major_version != '9'
  loop: "{{ container_modules }}"

- name: install packages
  dnf:
    name: "{{ podman_pkgs }}"
    state: latest

- name: Copy configuration files
  copy:
    src: "containers.conf"
    dest: "/etc/containers/containers.conf"
    owner: root
    group: root
    mode: 0644

- name: do the handlers before the service starts
  meta: flush_handlers

- name: activate podman user service
  systemd:
    name: podman
    state: restarted
    daemon-reload: yes
    scope: user
  become_user: zach

- name: activate podman system service
  systemd:
    name: "podman"
    state: restarted
    daemon-reload: yes