---
- name: install packages
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - vim
    - cockpit
    - podman
    - buildah

      # name: set chownership
      # file:
      #   path: /home/zach/.local/share/containers
      #   state: directory
      #   recurse: yes
      #   owner: zach
      #   group: zach
      #
      # name: set selinux for storage
      # sefcontext:
      #   target: '/home/zach/.local/share/containers(/.*)?'
      #   setype: 'container_var_lib_t'
      #   state: present
      # register: sel_chgd
      #
      # name: restore context
      # command: restorecon -R /home/zach/.local/share/containers
      # when: sel_chgd.changed

- name: activate podman user service
  systemd:
    name: io.podman
    state: restarted
    daemon-reload: yes
    scope: user
  become_user: zach
