---
- name: mc_server | install pre-reqs
  dnf:
    name: ['git', 'java-1.8.0-openjdk', 'tmux']
    state: latest

- name: mc_server | open port
  firewalld:
    port: "{{ item }}/tcp"
    state: enabled
    permanent: yes
  with_sequence: start=25565 end=25575

- name: mc_server | disable SELinux
  selinux:
    policy: targeted
    state: permissive

- name: mc_server | copy and create directories
  copy:
    src: "{{ item }}"
    dest: /srv/
    force: no
  loop: ['goat', 'bear']

- name: mc_server | link server.jar
  file:
    src: "/srv/{{ item }}/paper-59.jar"
    dest: "/srv/{{ item }}/server.jar"
    state: link
  loop: ['goat', 'bear']

- name: mc_server | copy server service files
  copy:
    src: "{{ item }}"
    dest: "/usr/lib/systemd/system/{{ item }}"
  loop: ['paper_goat.service', 'paper_bear.service']

- name: mc_server | enable_start the servers
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon-reload: yes
    enabled: true
  loop: ['paper_goat.service', 'paper_bear.service']
