---
- name: add the tailscale repo
  ansible.builtin.command: dnf config-manager --add-repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo

- name: install the tailscale rpm
  ansible.builtin.dnf:
    name: tailscale
    state: present

- name: start and enable ts service
  ansible.builtin.systemd:
    name: tailscaled
    state: started
    enabled: yes

- name: run the ts up
  ansible.builtin.shell: tailscale up | tee -a /tmp/url.txt
  async: 240
  poll: 0

- name: get the generated file
  ansible.builtin.slurp:
    src: /tmp/url.txt
  register: urls

- debug:
    msg: "{{ urls['content'] | b64decode }}"

    #- name: create the firefox tabs from the link
    #  command: "firefox --new-tab 
