---
dnsmasq_cli: >-
  -d -q --dhcp-range=192.168.1.1,proxy,255.255.255.0 --enable-tftp 
  --tftp-root=/var/lib/tftpboot --dhcp-userclass=set:ipxe,iPXE 
  --pxe-service=tag:#ipxe,x86PC,"PXE_chainload_to_iPXE",undionly.kpxe 
  --pxe-service=tag:ipxe,x86PC,"iPXE",http://matchbox.verboxen.org:8080/boot.ipxe 
  --pxe-service=tag:#ipxe,X86-64_EFI,"PXE_chainload_to_iPXE_UEFI",ipxe.efi 
  --pxe-service=tag:ipxe,X86-64_EFI,"iPXE_UEFI",http://matchbox.verboxen.org.com:8080/boot.ipxe 
  --log-queries --log-dhcp