---
- name: copy dotfiles
  ansible.builtin.copy:
    src: "{{ item.source }}"
    dest: "{{ item.dest }}"
    owner: zach
    group: zach
    mode: "{{ item.mode }}"
  loop: dotfiles

- name: set up directories
  ansible.builtin.file:
    path: "/home/zach/{{ item.dir }}"
    state: directory
    owner: zach
    group: zach
    mode: "{{ item.mode }}"
  loop: dotdirs

- name: find all remote pub keys
  ansible.builtin.find:
    paths: '/home/zach/.ssh'
    patterns: 'id*pub'
  register: host_pub_keys

- name: get all of the public keys
  ansible.builtin.fetch:
    dest: /home/zach/Ansible/playbooks/host_vars
    src: "/home/zach/.ssh/{{ item }}"
  loop: "{{ host_pub_keys.files.paths | list }}"
  register: pub_keys

    #- name: copy authorized keys
    #  ansible.posix.authorized_key:
    #    user: zach
    #    state: present
