---
# extra stuff from elsewheres
- name: set up poetry
  ansible.builtin.shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
  args:
    creates: "{{ ansible_user_dir }}/.poetry/bin/poetry"

- name: install pipx
  ansible.builtin.pip:
    name: pipx
    state: present
    extra_args: --user

- name: pipx do the path thing
  ansible.builtin.command: python3 -m pipx ensurepath

- name: curl up a kitty
  ansible.builtin.shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  args:
    creates: "{{ ansible_user_dir }}/.local/kitty.app/bin/kitty" 

- name: kitty on the left hand path
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.local/kitty.app/bin/kitty"
    dest: "{{ ansible_user_dir }}/.local/bin/kitty"
    state: link
