---
- name: install a few normal things
  ansible.builtin.dnf:
    name: ['tilix', 'vim', 'buildah', 'syncthing']
    state: present

- name: make vim right
  ansible.builtin.shell: |
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  become: yes
  become_user: zach

- name: start up user services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    daemon-reload: yes
    state: restarted
    scope: user
  become_user: zach
  loop:
    - syncthing
    - podman.socket
    - podman-auto-update.timer

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  become_user: zach

- name: install the flattened paks
  flatpak:
    name: "{{ item }}"
    state: present
    method: user
  become_user: zach
  loop: 
    - com.github.babluboy.bookworm
    - im.riot.Riot
    - info.mumble.Mumble
    - org.gnome.NetworkDisplays
    - com.github.tchx84.Flatseal
    - com.discordapp.Discord
    - com.bitwarden.desktop
    - org.gnome.Firmware
    - org.gnome.seahorse.Application
    - com.github.wwmm.easyeffects
    - org.gnome.Connections
    - com.github.fabiocolacio.marker
    - com.visualstudio.code
    - com.mattjakeman.ExtensionManager
    - com.github.childishgiant.mixer
    - org.signal.Signal
    - de.haeckerfelix.AudioSharing
