---
- name: install a few normal things
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - tilix
    - vim
    - buildah
    - syncthing

- name: start up user services
  systemd:
    name: "{{ item }}"
    enabled: yes
    daemon-reload: yes
    state: restarted
    scope: user
  become_user: zach
  loop:
    - syncthing
    - podman.socket
    - podman-auto-update.timer

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  become_user: zach

- name: install the flattened paks
  flatpak:
    name: "{{ item }}"
    state: present
    method: user
  become_user: zach
  loop: 
    - com.getpostman.Postman
    - com.github.babluboy.bookworm
    - com.mojang.Minecraft
    - im.riot.Riot
    - info.mumble.Mumble
    - org.gnome.Lollypop
    - org.gnome.NetworkDisplays
