---
- name: get installed pagackes
  package_facts:

- name: set up vscode ms keys
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: set up vscode repo
  ansible.builtin.yum_repository:
    name: vscode
    description: ms vscode
    file: vscode.repo
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: add rpmfusion repos
  dnf:
    name: "{{ rpmfusion_urls }}"
    state: installed
    
- name: remove the nano default
  ansible.builtin.dnf:
    name: nano-default-editor
    state: absent

- name: run the additional rpmfusion dnf commands
  shell: "{{ item }} -y"
  loop:
    - 'dnf groupupdate core'
    - 'dnf groupupdate sound-and-video'

- name: install a few normal things
  ansible.builtin.dnf:
    name: "{{ zachs_rpms }}"
    state: present

- name: swap mesa packages to freeworld 
  command: "dnf swap {{ item.from }} {{ item.to }} -y"
  register: swapped
  changed_when: swapped.rc == 0
  loop: "{{ rpm_swaps }}"
  when: 
    - ansible_package.facts['mesa-va-drivers'] is defined
    - ansible_package.facts['mesa-vdpau-drivers'] is defined
