---
- name: evaluate fedora version
  ansible.builtin.shell: rpm -E %fedora
  register: fedvers

- name: set up the rpmfusion free and nonfree repos
  ansible.builtin.dnf:
    name: ['https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedvers.stdout }}.noarch.rpm', 
      'https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedvers.stdout }}.noarch.rpm']
    state: present
    disable_gpg_check: yes

- name: run some dnf stuff as commands
  ansible.builtin.command: "{{ item }}"
  loop:
    - 'dnf groupupdate core -y'
    - 'dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y'
    - 'dnf groupupdate sound-and-video -y'
