---
- name: install certificate tools
  ansible.builtin.dnf:
    name: 'ca-certificates'
    state: present

- name: copy ssl pem and crt
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}{{ item.src }}"
    owner: root
    group: root 
    mode: "{{ item.mode }}"
  loop:
    - { 'src': 'GandiStandardSSLCA2.pem', 'dest': '/etc/pki/tls/certs/', 'mode': '0644' }
    - { 'src': 'fsck-it.org.crt', 'dest': '/etc/pki/tls/certs/', 'mode': '0644' }
    - { 'src': 'fsck-it.org.key', 'dest': '/etc/pki/tls/private/', 'mode': '0600' }

- name: install certificate to trust
  ansible.builtin.command: update-ca-trust