---
- name: dhcrelay | install dhcrelay 
  dnf:
    state: latest
    name: dhcp-relay

- name: dhcrelay | copy dhcrelay.conf
  copy:
    src: dhcrelay.conf
    dest: /etc/systemd/system/dhcrelay.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: dhcrelay | enable - start dhcrelay
  systemd:
    state: started
    name: dhcrelay
    daemon-reload: yes
    enabled: yes
   
