---
- name: named | install named
  dnf:
    state: latest
    name: "{{ item }}"
  with_items:
    - bind
    - lynx
    - mutt
    - wget
    - vim
    - git

- name: named | copy named.conf
  copy:
    src: named.conf
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0644
    backup: yes

- name: named | Copy rfc1912
  copy:
    src: named.rfc1912.zones
    dest: /etc/named.rfc1912.zones
    owner: root
    group: named
    mode: 0640
    backup: yes

- name: named | copy tsundoku zone
  copy:
    src: tsundoku.pw
    dest: /var/named/tsundoku.pw
    owner: root
    group: named
    mode: 0644
   
- name: named | copy host file
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

- name: named | enable - start named
  systemd:
    state: started
    name: named
    daemon-reload: yes
    enabled: yes
   
