---
additional_repo_pkgs:
  { '9': ['epel-release'], '8': ['epel-release'],
   '38': ['https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-38.noarch.rpm', 'https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-38.noarch.rpm'],
   '39': ['https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-39.noarch.rpm', 'https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-39.noarch.rpm'] }
