- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: start systemd-resolved
      systemd:
        name: systemd-resolved
        state: started

    - name: remove /etc/resolv.conf
      file:
        path: /etc/resolv.conf
        state: absent

    - name: link stub resolver
      file:
        src: /run/systemd/resolve/stub-resolv.conf
        dest: /etc/resolv.conf
        state: link

    - name: reload and restart
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: true
        enabled: true
      loop:
        - NetworkManager
        - systemd-resolved

- hosts: nameservers
  become: yes
  become_user: root
  roles:
    - coredns
