---
- hosts: localhost

  tasks:
    - name: install prometheus
      import_role:
        name: k3s
        tasks_from: install_prom.yml
      environment:
        K8S_AUTH_KUBECONFIG: '/home/zach/.kube/config.yaml'  
        K8S_AUTH_HOST: 'https://10.0.10.33:6443'
