---
- name: K3s_uninstall
  hosts: k8s
  become: true
  become_user: root
  tasks:
    - name: Uninstall servers
      ansible.builtin.command: /usr/local/bin/k3s-uninstall.sh
      when: '"controlplane" in group_names'

    - name: Remove old kubeconfig
      ansible.builtin.file:
        path: /home/zach/.kube/kubeconfig.yml
        state: absent
      failed_when: false

    - name: Uninstall workers
      ansible.builtin.command: /usr/local/bin/k3s-agent-uninstall.sh
      when: '"worker" in group_names'

    - name: Clear any previous erros
      ansible.builtin.meta: clear_host_errors

    - name: Run the clean up script
      ansible.builtin.shell: |
        curl -k https://raw.githubusercontent.com/rancherlabs/support-tools/master/extended-rancher-2-cleanup/extended-cleanup-rancher2.sh | bash
      when: '"k8s_wrkstn" not in group_names'
