- hosts: all
  become: yes
  tasks:
    - name: flush tables
      command: iptables -F

    - name: set alternatives
      command: "update-alternatives --set {{ item }} /usr/sbin/{{ item }}-legacy"
      loop:
        - iptables
        - ip6tables

    - name: gotta redoot now
      reboot:

    - name: install the stuff
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - python3-apt

    - name: add docker gpg key
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

    - name: add docker repo
      shell: >
        add-apt-repository "deb [arch=arm64] https://download.docker.com/linux/debian
        $(lsb_release -cs) stable"

    - name: install docker on raspbian
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
        state: latest

    - name: add docker group
      group:
        name: docker
        state: present

    - name: admin added to docker group
      user:
        name: zach
        groups: sudo,docker
        append: yes

