- name: 'Run coredns role'
  hosts: nameservers
  become: true
  become_user: root
  roles:
    - coredns

- name: 'Run nginx role'
  hosts: kanazawa
  become: true
  become_user: root
  roles:
    - rproxy_nginx
