- name: "Configure Servers"
  hosts: servers
  become: true
  become_user: root
  roles:
    - fedora.linux_system_roles.network
    - common
    - tailscale
    - systemd_resolved
    - podman
    - devel
    - server_no_sleep
