- hosts: servers
  become: yes
  become_user: root
  roles:
    - network
    - common
    - tailscale
    - podman
    - devel
    - server_no_sleep
#   - ssl

- hosts: nameservers
  become: yes
  become_user: root
  roles:
    - coredns
#   - ssl


