---
- hosts: zach
  tasks:
    - name: make the .kube directory
      file:
        path: "/home/{{ k3s_user }}/.kube"
        state: directory
        owner: "{{ k3s_user }}"
        group: "{{ k3s_user }}"
        mode: 0744

- hosts: initial_cp
  tasks:
    - name: get the kubeconfig file
      fetch:
        src: "/home/{{ k3s_user }}/.kube/kubeconfig.yml"
        dest: "/home/{{ k3s_user }}/.kube/"
        flat: yes
        owner: "{{ k3s_user }}"
        group: "{{ k3s_user }}"
        mode: 0644

- hosts: zach 
  become: yes
  become_user: root
  tasks:
    - name: set up environment variable on ansible control host
      lineinfile:
        path: "/home/{{ k3s_user }}/.bash_profile"
        line: "export KUBECONFIG=/home/{{ k3s_user }}/.kube/kubeconfig.yml"
        owner: "{{ k3s_user }}"
        group: "{{ k3s_user }}"
        mode: 0644
    
    - name: install kubectl on localhost
      ansible.builtin.dnf:
        name: kubernetes-client
        state: latest

    
    
    
    