- name: update_all
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: First install dnf plugin
      ansible.builtin.dnf:
        name: 'python3-dnf-plugins-core'
        state: installed

    - name: Now update it all
      ansible.builtin.dnf:
        name: '*'
        state: latest
      register: dnfupdate

    - name: Reboot
      ansible.builtin.reboot:
      when: dnfupdate.changed

    - name: DNF system update
      ansible.builtin.command: 'dnf system-upgrade download --releasever=38 -y'

    - name: DNF sys-up reboot
      ansible.builtin.command: 'dnf system-upgrade reboot -y'
